# Generated by Django 5.0.7 on 2024-10-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0002_alter_movie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
