# Generated by Django 5.0.7 on 2024-10-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0003_rename_content_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
