# Generated by Django 5.0.7 on 2024-10-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0006_alter_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
